// Copyright (c) 2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.9
// source: matchFunction.proto

package matchfunction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchFunction_GetStatCodes_FullMethodName    = "/accelbyte.matchmaking.matchfunction.MatchFunction/GetStatCodes"
	MatchFunction_ValidateTicket_FullMethodName  = "/accelbyte.matchmaking.matchfunction.MatchFunction/ValidateTicket"
	MatchFunction_EnrichTicket_FullMethodName    = "/accelbyte.matchmaking.matchfunction.MatchFunction/EnrichTicket"
	MatchFunction_MakeMatches_FullMethodName     = "/accelbyte.matchmaking.matchfunction.MatchFunction/MakeMatches"
	MatchFunction_BackfillMatches_FullMethodName = "/accelbyte.matchmaking.matchfunction.MatchFunction/BackfillMatches"
)

// MatchFunctionClient is the client API for MatchFunction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchFunctionClient interface {
	GetStatCodes(ctx context.Context, in *GetStatCodesRequest, opts ...grpc.CallOption) (*StatCodesResponse, error)
	ValidateTicket(ctx context.Context, in *ValidateTicketRequest, opts ...grpc.CallOption) (*ValidateTicketResponse, error)
	EnrichTicket(ctx context.Context, in *EnrichTicketRequest, opts ...grpc.CallOption) (*EnrichTicketResponse, error)
	MakeMatches(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MakeMatchesRequest, MatchResponse], error)
	BackfillMatches(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BackfillMakeMatchesRequest, BackfillResponse], error)
}

type matchFunctionClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchFunctionClient(cc grpc.ClientConnInterface) MatchFunctionClient {
	return &matchFunctionClient{cc}
}

func (c *matchFunctionClient) GetStatCodes(ctx context.Context, in *GetStatCodesRequest, opts ...grpc.CallOption) (*StatCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatCodesResponse)
	err := c.cc.Invoke(ctx, MatchFunction_GetStatCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchFunctionClient) ValidateTicket(ctx context.Context, in *ValidateTicketRequest, opts ...grpc.CallOption) (*ValidateTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTicketResponse)
	err := c.cc.Invoke(ctx, MatchFunction_ValidateTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchFunctionClient) EnrichTicket(ctx context.Context, in *EnrichTicketRequest, opts ...grpc.CallOption) (*EnrichTicketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichTicketResponse)
	err := c.cc.Invoke(ctx, MatchFunction_EnrichTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchFunctionClient) MakeMatches(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MakeMatchesRequest, MatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MatchFunction_ServiceDesc.Streams[0], MatchFunction_MakeMatches_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MakeMatchesRequest, MatchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchFunction_MakeMatchesClient = grpc.BidiStreamingClient[MakeMatchesRequest, MatchResponse]

func (c *matchFunctionClient) BackfillMatches(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BackfillMakeMatchesRequest, BackfillResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MatchFunction_ServiceDesc.Streams[1], MatchFunction_BackfillMatches_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackfillMakeMatchesRequest, BackfillResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchFunction_BackfillMatchesClient = grpc.BidiStreamingClient[BackfillMakeMatchesRequest, BackfillResponse]

// MatchFunctionServer is the server API for MatchFunction service.
// All implementations should embed UnimplementedMatchFunctionServer
// for forward compatibility.
type MatchFunctionServer interface {
	GetStatCodes(context.Context, *GetStatCodesRequest) (*StatCodesResponse, error)
	ValidateTicket(context.Context, *ValidateTicketRequest) (*ValidateTicketResponse, error)
	EnrichTicket(context.Context, *EnrichTicketRequest) (*EnrichTicketResponse, error)
	MakeMatches(grpc.BidiStreamingServer[MakeMatchesRequest, MatchResponse]) error
	BackfillMatches(grpc.BidiStreamingServer[BackfillMakeMatchesRequest, BackfillResponse]) error
}

// UnimplementedMatchFunctionServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchFunctionServer struct{}

func (UnimplementedMatchFunctionServer) GetStatCodes(context.Context, *GetStatCodesRequest) (*StatCodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatCodes not implemented")
}
func (UnimplementedMatchFunctionServer) ValidateTicket(context.Context, *ValidateTicketRequest) (*ValidateTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateTicket not implemented")
}
func (UnimplementedMatchFunctionServer) EnrichTicket(context.Context, *EnrichTicketRequest) (*EnrichTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrichTicket not implemented")
}
func (UnimplementedMatchFunctionServer) MakeMatches(grpc.BidiStreamingServer[MakeMatchesRequest, MatchResponse]) error {
	return status.Errorf(codes.Unimplemented, "method MakeMatches not implemented")
}
func (UnimplementedMatchFunctionServer) BackfillMatches(grpc.BidiStreamingServer[BackfillMakeMatchesRequest, BackfillResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BackfillMatches not implemented")
}
func (UnimplementedMatchFunctionServer) testEmbeddedByValue() {}

// UnsafeMatchFunctionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchFunctionServer will
// result in compilation errors.
type UnsafeMatchFunctionServer interface {
	mustEmbedUnimplementedMatchFunctionServer()
}

func RegisterMatchFunctionServer(s grpc.ServiceRegistrar, srv MatchFunctionServer) {
	// If the following call pancis, it indicates UnimplementedMatchFunctionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchFunction_ServiceDesc, srv)
}

func _MatchFunction_GetStatCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchFunctionServer).GetStatCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchFunction_GetStatCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchFunctionServer).GetStatCodes(ctx, req.(*GetStatCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchFunction_ValidateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchFunctionServer).ValidateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchFunction_ValidateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchFunctionServer).ValidateTicket(ctx, req.(*ValidateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchFunction_EnrichTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchFunctionServer).EnrichTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchFunction_EnrichTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchFunctionServer).EnrichTicket(ctx, req.(*EnrichTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchFunction_MakeMatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MatchFunctionServer).MakeMatches(&grpc.GenericServerStream[MakeMatchesRequest, MatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchFunction_MakeMatchesServer = grpc.BidiStreamingServer[MakeMatchesRequest, MatchResponse]

func _MatchFunction_BackfillMatches_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MatchFunctionServer).BackfillMatches(&grpc.GenericServerStream[BackfillMakeMatchesRequest, BackfillResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchFunction_BackfillMatchesServer = grpc.BidiStreamingServer[BackfillMakeMatchesRequest, BackfillResponse]

// MatchFunction_ServiceDesc is the grpc.ServiceDesc for MatchFunction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchFunction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.matchmaking.matchfunction.MatchFunction",
	HandlerType: (*MatchFunctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatCodes",
			Handler:    _MatchFunction_GetStatCodes_Handler,
		},
		{
			MethodName: "ValidateTicket",
			Handler:    _MatchFunction_ValidateTicket_Handler,
		},
		{
			MethodName: "EnrichTicket",
			Handler:    _MatchFunction_EnrichTicket_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MakeMatches",
			Handler:       _MatchFunction_MakeMatches_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "BackfillMatches",
			Handler:       _MatchFunction_BackfillMatches_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "matchFunction.proto",
}
