// Copyright (c) 2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: matchFunction.proto

package matchfunction

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetStatCodes
type GetStatCodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         *Rules                 `protobuf:"bytes,1,opt,name=rules,proto3" json:"rules,omitempty"` // Rules JSON, can be used to derive stat codes based on the rule.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatCodesRequest) Reset() {
	*x = GetStatCodesRequest{}
	mi := &file_matchFunction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatCodesRequest) ProtoMessage() {}

func (x *GetStatCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatCodesRequest.ProtoReflect.Descriptor instead.
func (*GetStatCodesRequest) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatCodesRequest) GetRules() *Rules {
	if x != nil {
		return x.Rules
	}
	return nil
}

type StatCodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"` // List of stat code names (attributes).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatCodesResponse) Reset() {
	*x = StatCodesResponse{}
	mi := &file_matchFunction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatCodesResponse) ProtoMessage() {}

func (x *StatCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatCodesResponse.ProtoReflect.Descriptor instead.
func (*StatCodesResponse) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{1}
}

func (x *StatCodesResponse) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

// ValidateTicket
type ValidateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"` // Ticket that needs to be validated against the rules.
	Rules         *Rules                 `protobuf:"bytes,2,opt,name=rules,proto3" json:"rules,omitempty"`   // Matchmaking rules used to validate the ticket.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTicketRequest) Reset() {
	*x = ValidateTicketRequest{}
	mi := &file_matchFunction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTicketRequest) ProtoMessage() {}

func (x *ValidateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTicketRequest.ProtoReflect.Descriptor instead.
func (*ValidateTicketRequest) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTicketRequest) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *ValidateTicketRequest) GetRules() *Rules {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ValidateTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValidTicket   bool                   `protobuf:"varint,1,opt,name=valid_ticket,json=validTicket,proto3" json:"valid_ticket,omitempty"` // True if ticket is valid.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTicketResponse) Reset() {
	*x = ValidateTicketResponse{}
	mi := &file_matchFunction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTicketResponse) ProtoMessage() {}

func (x *ValidateTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTicketResponse.ProtoReflect.Descriptor instead.
func (*ValidateTicketResponse) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTicketResponse) GetValidTicket() bool {
	if x != nil {
		return x.ValidTicket
	}
	return false
}

// EnrichTicket
type EnrichTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"` // Ticket to be enriched; for example, add fields into ticket_attributes
	Rules         *Rules                 `protobuf:"bytes,2,opt,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichTicketRequest) Reset() {
	*x = EnrichTicketRequest{}
	mi := &file_matchFunction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichTicketRequest) ProtoMessage() {}

func (x *EnrichTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichTicketRequest.ProtoReflect.Descriptor instead.
func (*EnrichTicketRequest) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{4}
}

func (x *EnrichTicketRequest) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *EnrichTicketRequest) GetRules() *Rules {
	if x != nil {
		return x.Rules
	}
	return nil
}

type EnrichTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        *Ticket                `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"` // Returned enriched ticket.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichTicketResponse) Reset() {
	*x = EnrichTicketResponse{}
	mi := &file_matchFunction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichTicketResponse) ProtoMessage() {}

func (x *EnrichTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichTicketResponse.ProtoReflect.Descriptor instead.
func (*EnrichTicketResponse) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{5}
}

func (x *EnrichTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

// Make Matches
type MakeMatchesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*MakeMatchesRequest_Parameters
	//	*MakeMatchesRequest_Ticket
	RequestType   isMakeMatchesRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMatchesRequest) Reset() {
	*x = MakeMatchesRequest{}
	mi := &file_matchFunction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMatchesRequest) ProtoMessage() {}

func (x *MakeMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMatchesRequest.ProtoReflect.Descriptor instead.
func (*MakeMatchesRequest) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{6}
}

func (x *MakeMatchesRequest) GetRequestType() isMakeMatchesRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *MakeMatchesRequest) GetParameters() *MakeMatchesRequest_MakeMatchesParameters {
	if x != nil {
		if x, ok := x.RequestType.(*MakeMatchesRequest_Parameters); ok {
			return x.Parameters
		}
	}
	return nil
}

func (x *MakeMatchesRequest) GetTicket() *Ticket {
	if x != nil {
		if x, ok := x.RequestType.(*MakeMatchesRequest_Ticket); ok {
			return x.Ticket
		}
	}
	return nil
}

type isMakeMatchesRequest_RequestType interface {
	isMakeMatchesRequest_RequestType()
}

type MakeMatchesRequest_Parameters struct {
	Parameters *MakeMatchesRequest_MakeMatchesParameters `protobuf:"bytes,1,opt,name=parameters,proto3,oneof"` // sent exactly once
}

type MakeMatchesRequest_Ticket struct {
	Ticket *Ticket `protobuf:"bytes,2,opt,name=ticket,proto3,oneof"` // sent 0..N times; all tickets MUST share the same match_pool the stream. All tickets in the stream must share the same match_pool.
}

func (*MakeMatchesRequest_Parameters) isMakeMatchesRequest_RequestType() {}

func (*MakeMatchesRequest_Ticket) isMakeMatchesRequest_RequestType() {}

type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_matchFunction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{7}
}

func (x *MatchResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AbTraceId     string                 `protobuf:"bytes,1,opt,name=ab_trace_id,json=abTraceId,proto3" json:"ab_trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_matchFunction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{8}
}

func (x *Scope) GetAbTraceId() string {
	if x != nil {
		return x.AbTraceId
	}
	return ""
}

type Rules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"` // Raw rules JSON consumed by match function to configure matching, validation, and backfill. Developers can define any rule they like.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rules) Reset() {
	*x = Rules{}
	mi := &file_matchFunction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rules) ProtoMessage() {}

func (x *Rules) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rules.ProtoReflect.Descriptor instead.
func (*Rules) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{9}
}

func (x *Rules) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type Party struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"` // Party/session identifier.
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // Players belonging to this party, populated from the ticket's players.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Party) Reset() {
	*x = Party{}
	mi := &file_matchFunction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Party) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Party) ProtoMessage() {}

func (x *Party) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Party.ProtoReflect.Descriptor instead.
func (*Party) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{10}
}

func (x *Party) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *Party) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type Match struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tickets           []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`                                              // Tickets used to form this match
	Teams             []*Match_Team          `protobuf:"bytes,2,rep,name=teams,proto3" json:"teams,omitempty"`                                                  // Team assignments produced by matching logic
	RegionPreferences []string               `protobuf:"bytes,3,rep,name=region_preferences,json=regionPreferences,proto3" json:"region_preferences,omitempty"` // Ordered region preferences for this match
	MatchAttributes   *structpb.Struct       `protobuf:"bytes,4,opt,name=match_attributes,json=matchAttributes,proto3" json:"match_attributes,omitempty"`       // Attributes for the session that can be used for backfill matches.
	Backfill          bool                   `protobuf:"varint,5,opt,name=backfill,proto3" json:"backfill,omitempty"`                                           // True when session is not full and need more players, the session will be added to backfill queue.
	ServerName        string                 `protobuf:"bytes,6,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ClientVersion     string                 `protobuf:"bytes,7,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ServerPool        *ServerPool            `protobuf:"bytes,8,opt,name=server_pool,json=serverPool,proto3" json:"server_pool,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_matchFunction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{11}
}

func (x *Match) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *Match) GetTeams() []*Match_Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *Match) GetRegionPreferences() []string {
	if x != nil {
		return x.RegionPreferences
	}
	return nil
}

func (x *Match) GetMatchAttributes() *structpb.Struct {
	if x != nil {
		return x.MatchAttributes
	}
	return nil
}

func (x *Match) GetBackfill() bool {
	if x != nil {
		return x.Backfill
	}
	return false
}

func (x *Match) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Match) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Match) GetServerPool() *ServerPool {
	if x != nil {
		return x.ServerPool
	}
	return nil
}

type ServerPool struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerProvider string                 `protobuf:"bytes,1,opt,name=server_provider,json=serverProvider,proto3" json:"server_provider,omitempty"`
	Deployment     string                 `protobuf:"bytes,2,opt,name=deployment,proto3" json:"deployment,omitempty"`
	ClaimKeys      []string               `protobuf:"bytes,3,rep,name=claim_keys,json=claimKeys,proto3" json:"claim_keys,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerPool) Reset() {
	*x = ServerPool{}
	mi := &file_matchFunction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPool) ProtoMessage() {}

func (x *ServerPool) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPool.ProtoReflect.Descriptor instead.
func (*ServerPool) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{12}
}

func (x *ServerPool) GetServerProvider() string {
	if x != nil {
		return x.ServerProvider
	}
	return ""
}

func (x *ServerPool) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

func (x *ServerPool) GetClaimKeys() []string {
	if x != nil {
		return x.ClaimKeys
	}
	return nil
}

type Ticket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TicketId         string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	MatchPool        string                 `protobuf:"bytes,2,opt,name=match_pool,json=matchPool,proto3" json:"match_pool,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                                                                            // Ticket creation time.
	Players          []*Ticket_PlayerData   `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`                                                                                // A ticket can contain multiple players; MMR for a ticket is usually the average of player values.
	TicketAttributes *structpb.Struct       `protobuf:"bytes,5,opt,name=ticket_attributes,json=ticketAttributes,proto3" json:"ticket_attributes,omitempty"`                                      // map[string]any of ticket attributes. These attributes can be used to match with other tickets.
	Latencies        map[string]int64       `protobuf:"bytes,6,rep,name=latencies,proto3" json:"latencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Map of AWS region to player latencies in ms
	PartySessionId   string                 `protobuf:"bytes,7,opt,name=party_session_id,json=partySessionId,proto3" json:"party_session_id,omitempty"`                                          // If present, this is a party ticket. All players MUST be assigned as a unit.
	Namespace        string                 `protobuf:"bytes,8,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ExcludedSessions []string               `protobuf:"bytes,9,rep,name=excluded_sessions,json=excludedSessions,proto3" json:"excluded_sessions,omitempty"` // A collection of past game session IDs that the user has chosen not to be matched with again.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_matchFunction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{13}
}

func (x *Ticket) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *Ticket) GetMatchPool() string {
	if x != nil {
		return x.MatchPool
	}
	return ""
}

func (x *Ticket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Ticket) GetPlayers() []*Ticket_PlayerData {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Ticket) GetTicketAttributes() *structpb.Struct {
	if x != nil {
		return x.TicketAttributes
	}
	return nil
}

func (x *Ticket) GetLatencies() map[string]int64 {
	if x != nil {
		return x.Latencies
	}
	return nil
}

func (x *Ticket) GetPartySessionId() string {
	if x != nil {
		return x.PartySessionId
	}
	return ""
}

func (x *Ticket) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Ticket) GetExcludedSessions() []string {
	if x != nil {
		return x.ExcludedSessions
	}
	return nil
}

// Backfill
type BackfillProposal struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	BackfillTicketId string                   `protobuf:"bytes,1,opt,name=backfill_ticket_id,json=backfillTicketId,proto3" json:"backfill_ticket_id,omitempty"`
	CreatedAt        *timestamppb.Timestamp   `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	AddedTickets     []*Ticket                `protobuf:"bytes,3,rep,name=added_tickets,json=addedTickets,proto3" json:"added_tickets,omitempty"`    // New tickets being added to the match.
	ProposedTeams    []*BackfillProposal_Team `protobuf:"bytes,4,rep,name=proposed_teams,json=proposedTeams,proto3" json:"proposed_teams,omitempty"` // Updated team composition after backfill.
	ProposalId       string                   `protobuf:"bytes,5,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`          // UUID (no hyphens)
	MatchPool        string                   `protobuf:"bytes,6,opt,name=match_pool,json=matchPool,proto3" json:"match_pool,omitempty"`
	MatchSessionId   string                   `protobuf:"bytes,7,opt,name=match_session_id,json=matchSessionId,proto3" json:"match_session_id,omitempty"` // The session ID of the match being updated.
	Attributes       *structpb.Struct         `protobuf:"bytes,8,opt,name=attributes,proto3" json:"attributes,omitempty"`                                 // Attributes for the session that can be used for backfill proposed
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BackfillProposal) Reset() {
	*x = BackfillProposal{}
	mi := &file_matchFunction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillProposal) ProtoMessage() {}

func (x *BackfillProposal) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillProposal.ProtoReflect.Descriptor instead.
func (*BackfillProposal) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{14}
}

func (x *BackfillProposal) GetBackfillTicketId() string {
	if x != nil {
		return x.BackfillTicketId
	}
	return ""
}

func (x *BackfillProposal) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BackfillProposal) GetAddedTickets() []*Ticket {
	if x != nil {
		return x.AddedTickets
	}
	return nil
}

func (x *BackfillProposal) GetProposedTeams() []*BackfillProposal_Team {
	if x != nil {
		return x.ProposedTeams
	}
	return nil
}

func (x *BackfillProposal) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *BackfillProposal) GetMatchPool() string {
	if x != nil {
		return x.MatchPool
	}
	return ""
}

func (x *BackfillProposal) GetMatchSessionId() string {
	if x != nil {
		return x.MatchSessionId
	}
	return ""
}

func (x *BackfillProposal) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Backfill Make Matches
type BackfillMakeMatchesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestType:
	//
	//	*BackfillMakeMatchesRequest_Parameters
	//	*BackfillMakeMatchesRequest_BackfillTicket
	//	*BackfillMakeMatchesRequest_Ticket
	RequestType   isBackfillMakeMatchesRequest_RequestType `protobuf_oneof:"request_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillMakeMatchesRequest) Reset() {
	*x = BackfillMakeMatchesRequest{}
	mi := &file_matchFunction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillMakeMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillMakeMatchesRequest) ProtoMessage() {}

func (x *BackfillMakeMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillMakeMatchesRequest.ProtoReflect.Descriptor instead.
func (*BackfillMakeMatchesRequest) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{15}
}

func (x *BackfillMakeMatchesRequest) GetRequestType() isBackfillMakeMatchesRequest_RequestType {
	if x != nil {
		return x.RequestType
	}
	return nil
}

func (x *BackfillMakeMatchesRequest) GetParameters() *BackfillMakeMatchesRequest_MakeMatchesParameters {
	if x != nil {
		if x, ok := x.RequestType.(*BackfillMakeMatchesRequest_Parameters); ok {
			return x.Parameters
		}
	}
	return nil
}

func (x *BackfillMakeMatchesRequest) GetBackfillTicket() *BackfillTicket {
	if x != nil {
		if x, ok := x.RequestType.(*BackfillMakeMatchesRequest_BackfillTicket); ok {
			return x.BackfillTicket
		}
	}
	return nil
}

func (x *BackfillMakeMatchesRequest) GetTicket() *Ticket {
	if x != nil {
		if x, ok := x.RequestType.(*BackfillMakeMatchesRequest_Ticket); ok {
			return x.Ticket
		}
	}
	return nil
}

type isBackfillMakeMatchesRequest_RequestType interface {
	isBackfillMakeMatchesRequest_RequestType()
}

type BackfillMakeMatchesRequest_Parameters struct {
	Parameters *BackfillMakeMatchesRequest_MakeMatchesParameters `protobuf:"bytes,1,opt,name=parameters,proto3,oneof"` // sent exactly once
}

type BackfillMakeMatchesRequest_BackfillTicket struct {
	BackfillTicket *BackfillTicket `protobuf:"bytes,2,opt,name=backfill_ticket,json=backfillTicket,proto3,oneof"` // sent 0..N times; all tickets MUST share the same match_pool
}

type BackfillMakeMatchesRequest_Ticket struct {
	Ticket *Ticket `protobuf:"bytes,3,opt,name=ticket,proto3,oneof"` // sent 0..N times; all tickets MUST share the same match_pool
}

func (*BackfillMakeMatchesRequest_Parameters) isBackfillMakeMatchesRequest_RequestType() {}

func (*BackfillMakeMatchesRequest_BackfillTicket) isBackfillMakeMatchesRequest_RequestType() {}

func (*BackfillMakeMatchesRequest_Ticket) isBackfillMakeMatchesRequest_RequestType() {}

type BackfillResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BackfillProposal *BackfillProposal      `protobuf:"bytes,1,opt,name=backfill_proposal,json=backfillProposal,proto3" json:"backfill_proposal,omitempty"` // Proposal built from BackfillMatches to update an ongoing session
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BackfillResponse) Reset() {
	*x = BackfillResponse{}
	mi := &file_matchFunction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillResponse) ProtoMessage() {}

func (x *BackfillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillResponse.ProtoReflect.Descriptor instead.
func (*BackfillResponse) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{16}
}

func (x *BackfillResponse) GetBackfillProposal() *BackfillProposal {
	if x != nil {
		return x.BackfillProposal
	}
	return nil
}

// BackfillTicket represent ticket that created by ongoing session
type BackfillTicket struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	TicketId       string                       `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"` // backfill ticket ID
	MatchPool      string                       `protobuf:"bytes,2,opt,name=match_pool,json=matchPool,proto3" json:"match_pool,omitempty"`
	CreatedAt      *timestamppb.Timestamp       `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	PartialMatch   *BackfillTicket_PartialMatch `protobuf:"bytes,4,opt,name=partial_match,json=partialMatch,proto3" json:"partial_match,omitempty"`
	MatchSessionId string                       `protobuf:"bytes,5,opt,name=match_session_id,json=matchSessionId,proto3" json:"match_session_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackfillTicket) Reset() {
	*x = BackfillTicket{}
	mi := &file_matchFunction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillTicket) ProtoMessage() {}

func (x *BackfillTicket) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillTicket.ProtoReflect.Descriptor instead.
func (*BackfillTicket) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{17}
}

func (x *BackfillTicket) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *BackfillTicket) GetMatchPool() string {
	if x != nil {
		return x.MatchPool
	}
	return ""
}

func (x *BackfillTicket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BackfillTicket) GetPartialMatch() *BackfillTicket_PartialMatch {
	if x != nil {
		return x.PartialMatch
	}
	return nil
}

func (x *BackfillTicket) GetMatchSessionId() string {
	if x != nil {
		return x.MatchSessionId
	}
	return ""
}

// MUST be the first message on the stream.
// All subsequent messages on this stream are tickets for a single logical batch.
type MakeMatchesRequest_MakeMatchesParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Scope *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// Raw Rules JSON defining the strategy (Alliance, MMR windows, regions, etc.)
	Rules *Rules `protobuf:"bytes,2,opt,name=rules,proto3" json:"rules,omitempty"`
	// Monotonic tick identifier; used for server logs and idempotence advisory.
	TickId        uint64 `protobuf:"varint,3,opt,name=tickId,proto3" json:"tickId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMatchesRequest_MakeMatchesParameters) Reset() {
	*x = MakeMatchesRequest_MakeMatchesParameters{}
	mi := &file_matchFunction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMatchesRequest_MakeMatchesParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMatchesRequest_MakeMatchesParameters) ProtoMessage() {}

func (x *MakeMatchesRequest_MakeMatchesParameters) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMatchesRequest_MakeMatchesParameters.ProtoReflect.Descriptor instead.
func (*MakeMatchesRequest_MakeMatchesParameters) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{6, 0}
}

func (x *MakeMatchesRequest_MakeMatchesParameters) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *MakeMatchesRequest_MakeMatchesParameters) GetRules() *Rules {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *MakeMatchesRequest_MakeMatchesParameters) GetTickId() uint64 {
	if x != nil {
		return x.TickId
	}
	return 0
}

type Match_Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // Users assigned to this team (aggregated from tickets)
	Parties       []*Party               `protobuf:"bytes,2,rep,name=parties,proto3" json:"parties,omitempty"`                // Parties included on this team (constructed from Ticket.party_session_id)
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`    // UUID (no hyphens)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match_Team) Reset() {
	*x = Match_Team{}
	mi := &file_matchFunction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match_Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match_Team) ProtoMessage() {}

func (x *Match_Team) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match_Team.ProtoReflect.Descriptor instead.
func (*Match_Team) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{11, 0}
}

func (x *Match_Team) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *Match_Team) GetParties() []*Party {
	if x != nil {
		return x.Parties
	}
	return nil
}

func (x *Match_Team) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type Ticket_PlayerData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"` // map[string]any of the player attributes. ELO or MMR is stored here as map[string]float64.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket_PlayerData) Reset() {
	*x = Ticket_PlayerData{}
	mi := &file_matchFunction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket_PlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket_PlayerData) ProtoMessage() {}

func (x *Ticket_PlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket_PlayerData.ProtoReflect.Descriptor instead.
func (*Ticket_PlayerData) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{13, 0}
}

func (x *Ticket_PlayerData) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Ticket_PlayerData) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type BackfillProposal_Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Parties       []*Party               `protobuf:"bytes,2,rep,name=parties,proto3" json:"parties,omitempty"`
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // UUID (no hyphens)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillProposal_Team) Reset() {
	*x = BackfillProposal_Team{}
	mi := &file_matchFunction_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillProposal_Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillProposal_Team) ProtoMessage() {}

func (x *BackfillProposal_Team) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillProposal_Team.ProtoReflect.Descriptor instead.
func (*BackfillProposal_Team) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{14, 0}
}

func (x *BackfillProposal_Team) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *BackfillProposal_Team) GetParties() []*Party {
	if x != nil {
		return x.Parties
	}
	return nil
}

func (x *BackfillProposal_Team) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// MUST be the first message on the stream.
// All subsequent messages on this stream are tickets for a single logical batch.
type BackfillMakeMatchesRequest_MakeMatchesParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Scope *Scope                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// Raw Rules JSON defining the strategy (Alliance, MMR windows, regions, etc.)
	Rules *Rules `protobuf:"bytes,2,opt,name=rules,proto3" json:"rules,omitempty"`
	// Monotonic tick identifier; used for server logs and idempotence advisory.
	TickId        uint64 `protobuf:"varint,3,opt,name=tickId,proto3" json:"tickId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillMakeMatchesRequest_MakeMatchesParameters) Reset() {
	*x = BackfillMakeMatchesRequest_MakeMatchesParameters{}
	mi := &file_matchFunction_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillMakeMatchesRequest_MakeMatchesParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillMakeMatchesRequest_MakeMatchesParameters) ProtoMessage() {}

func (x *BackfillMakeMatchesRequest_MakeMatchesParameters) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillMakeMatchesRequest_MakeMatchesParameters.ProtoReflect.Descriptor instead.
func (*BackfillMakeMatchesRequest_MakeMatchesParameters) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{15, 0}
}

func (x *BackfillMakeMatchesRequest_MakeMatchesParameters) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *BackfillMakeMatchesRequest_MakeMatchesParameters) GetRules() *Rules {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *BackfillMakeMatchesRequest_MakeMatchesParameters) GetTickId() uint64 {
	if x != nil {
		return x.TickId
	}
	return 0
}

type BackfillTicket_Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Parties       []*Party               `protobuf:"bytes,2,rep,name=parties,proto3" json:"parties,omitempty"`
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // UUID (no hyphens)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillTicket_Team) Reset() {
	*x = BackfillTicket_Team{}
	mi := &file_matchFunction_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillTicket_Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillTicket_Team) ProtoMessage() {}

func (x *BackfillTicket_Team) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillTicket_Team.ProtoReflect.Descriptor instead.
func (*BackfillTicket_Team) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{17, 0}
}

func (x *BackfillTicket_Team) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *BackfillTicket_Team) GetParties() []*Party {
	if x != nil {
		return x.Parties
	}
	return nil
}

func (x *BackfillTicket_Team) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type BackfillTicket_PartialMatch struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tickets           []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`                                              // All tickets that were matched together
	Teams             []*BackfillTicket_Team `protobuf:"bytes,2,rep,name=teams,proto3" json:"teams,omitempty"`                                                  // Team assignments for the matched players of the current session
	RegionPreferences []string               `protobuf:"bytes,3,rep,name=region_preferences,json=regionPreferences,proto3" json:"region_preferences,omitempty"` // Preferred regions for this match (typically one item: the region where the DS is running)
	MatchAttributes   *structpb.Struct       `protobuf:"bytes,4,opt,name=match_attributes,json=matchAttributes,proto3" json:"match_attributes,omitempty"`       // Custom attributes of the session
	Backfill          bool                   `protobuf:"varint,5,opt,name=backfill,proto3" json:"backfill,omitempty"`                                           // False for complete matches; true if more players are desired
	ServerName        string                 `protobuf:"bytes,6,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`                      // DS server name, can be used for directing the match session to the local DS
	ClientVersion     string                 `protobuf:"bytes,7,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`             // Specific game version that the DS supports
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BackfillTicket_PartialMatch) Reset() {
	*x = BackfillTicket_PartialMatch{}
	mi := &file_matchFunction_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillTicket_PartialMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillTicket_PartialMatch) ProtoMessage() {}

func (x *BackfillTicket_PartialMatch) ProtoReflect() protoreflect.Message {
	mi := &file_matchFunction_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillTicket_PartialMatch.ProtoReflect.Descriptor instead.
func (*BackfillTicket_PartialMatch) Descriptor() ([]byte, []int) {
	return file_matchFunction_proto_rawDescGZIP(), []int{17, 1}
}

func (x *BackfillTicket_PartialMatch) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *BackfillTicket_PartialMatch) GetTeams() []*BackfillTicket_Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *BackfillTicket_PartialMatch) GetRegionPreferences() []string {
	if x != nil {
		return x.RegionPreferences
	}
	return nil
}

func (x *BackfillTicket_PartialMatch) GetMatchAttributes() *structpb.Struct {
	if x != nil {
		return x.MatchAttributes
	}
	return nil
}

func (x *BackfillTicket_PartialMatch) GetBackfill() bool {
	if x != nil {
		return x.Backfill
	}
	return false
}

func (x *BackfillTicket_PartialMatch) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *BackfillTicket_PartialMatch) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

var File_matchFunction_proto protoreflect.FileDescriptor

const file_matchFunction_proto_rawDesc = "" +
	"\n" +
	"\x13matchFunction.proto\x12#accelbyte.matchmaking.matchfunction\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\x13GetStatCodesRequest\x12@\n" +
	"\x05rules\x18\x01 \x01(\v2*.accelbyte.matchmaking.matchfunction.RulesR\x05rules\")\n" +
	"\x11StatCodesResponse\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"\x9e\x01\n" +
	"\x15ValidateTicketRequest\x12C\n" +
	"\x06ticket\x18\x01 \x01(\v2+.accelbyte.matchmaking.matchfunction.TicketR\x06ticket\x12@\n" +
	"\x05rules\x18\x02 \x01(\v2*.accelbyte.matchmaking.matchfunction.RulesR\x05rules\";\n" +
	"\x16ValidateTicketResponse\x12!\n" +
	"\fvalid_ticket\x18\x01 \x01(\bR\vvalidTicket\"\x9c\x01\n" +
	"\x13EnrichTicketRequest\x12C\n" +
	"\x06ticket\x18\x01 \x01(\v2+.accelbyte.matchmaking.matchfunction.TicketR\x06ticket\x12@\n" +
	"\x05rules\x18\x02 \x01(\v2*.accelbyte.matchmaking.matchfunction.RulesR\x05rules\"[\n" +
	"\x14EnrichTicketResponse\x12C\n" +
	"\x06ticket\x18\x01 \x01(\v2+.accelbyte.matchmaking.matchfunction.TicketR\x06ticket\"\x92\x03\n" +
	"\x12MakeMatchesRequest\x12o\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2M.accelbyte.matchmaking.matchfunction.MakeMatchesRequest.MakeMatchesParametersH\x00R\n" +
	"parameters\x12E\n" +
	"\x06ticket\x18\x02 \x01(\v2+.accelbyte.matchmaking.matchfunction.TicketH\x00R\x06ticket\x1a\xb3\x01\n" +
	"\x15MakeMatchesParameters\x12@\n" +
	"\x05scope\x18\x01 \x01(\v2*.accelbyte.matchmaking.matchfunction.ScopeR\x05scope\x12@\n" +
	"\x05rules\x18\x02 \x01(\v2*.accelbyte.matchmaking.matchfunction.RulesR\x05rules\x12\x16\n" +
	"\x06tickId\x18\x03 \x01(\x04R\x06tickIdB\x0e\n" +
	"\frequest_type\"Q\n" +
	"\rMatchResponse\x12@\n" +
	"\x05match\x18\x01 \x01(\v2*.accelbyte.matchmaking.matchfunction.MatchR\x05match\"'\n" +
	"\x05Scope\x12\x1e\n" +
	"\vab_trace_id\x18\x01 \x01(\tR\tabTraceId\"\x1b\n" +
	"\x05Rules\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"=\n" +
	"\x05Party\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"\xc1\x04\n" +
	"\x05Match\x12E\n" +
	"\atickets\x18\x01 \x03(\v2+.accelbyte.matchmaking.matchfunction.TicketR\atickets\x12E\n" +
	"\x05teams\x18\x02 \x03(\v2/.accelbyte.matchmaking.matchfunction.Match.TeamR\x05teams\x12-\n" +
	"\x12region_preferences\x18\x03 \x03(\tR\x11regionPreferences\x12B\n" +
	"\x10match_attributes\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x0fmatchAttributes\x12\x1a\n" +
	"\bbackfill\x18\x05 \x01(\bR\bbackfill\x12\x1f\n" +
	"\vserver_name\x18\x06 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x0eclient_version\x18\a \x01(\tR\rclientVersion\x12P\n" +
	"\vserver_pool\x18\b \x01(\v2/.accelbyte.matchmaking.matchfunction.ServerPoolR\n" +
	"serverPool\x1a\x80\x01\n" +
	"\x04Team\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12D\n" +
	"\aparties\x18\x02 \x03(\v2*.accelbyte.matchmaking.matchfunction.PartyR\aparties\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\"t\n" +
	"\n" +
	"ServerPool\x12'\n" +
	"\x0fserver_provider\x18\x01 \x01(\tR\x0eserverProvider\x12\x1e\n" +
	"\n" +
	"deployment\x18\x02 \x01(\tR\n" +
	"deployment\x12\x1d\n" +
	"\n" +
	"claim_keys\x18\x03 \x03(\tR\tclaimKeys\"\x87\x05\n" +
	"\x06Ticket\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1d\n" +
	"\n" +
	"match_pool\x18\x02 \x01(\tR\tmatchPool\x128\n" +
	"\tCreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12P\n" +
	"\aplayers\x18\x04 \x03(\v26.accelbyte.matchmaking.matchfunction.Ticket.PlayerDataR\aplayers\x12D\n" +
	"\x11ticket_attributes\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x10ticketAttributes\x12X\n" +
	"\tlatencies\x18\x06 \x03(\v2:.accelbyte.matchmaking.matchfunction.Ticket.LatenciesEntryR\tlatencies\x12(\n" +
	"\x10party_session_id\x18\a \x01(\tR\x0epartySessionId\x12\x1c\n" +
	"\tnamespace\x18\b \x01(\tR\tnamespace\x12+\n" +
	"\x11excluded_sessions\x18\t \x03(\tR\x10excludedSessions\x1ab\n" +
	"\n" +
	"PlayerData\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x127\n" +
	"\n" +
	"attributes\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x1a<\n" +
	"\x0eLatenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xd5\x04\n" +
	"\x10BackfillProposal\x12,\n" +
	"\x12backfill_ticket_id\x18\x01 \x01(\tR\x10backfillTicketId\x128\n" +
	"\tCreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12P\n" +
	"\radded_tickets\x18\x03 \x03(\v2+.accelbyte.matchmaking.matchfunction.TicketR\faddedTickets\x12a\n" +
	"\x0eproposed_teams\x18\x04 \x03(\v2:.accelbyte.matchmaking.matchfunction.BackfillProposal.TeamR\rproposedTeams\x12\x1f\n" +
	"\vproposal_id\x18\x05 \x01(\tR\n" +
	"proposalId\x12\x1d\n" +
	"\n" +
	"match_pool\x18\x06 \x01(\tR\tmatchPool\x12(\n" +
	"\x10match_session_id\x18\a \x01(\tR\x0ematchSessionId\x127\n" +
	"\n" +
	"attributes\x18\b \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x1a\x80\x01\n" +
	"\x04Team\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12D\n" +
	"\aparties\x18\x02 \x03(\v2*.accelbyte.matchmaking.matchfunction.PartyR\aparties\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\"\x82\x04\n" +
	"\x1aBackfillMakeMatchesRequest\x12w\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2U.accelbyte.matchmaking.matchfunction.BackfillMakeMatchesRequest.MakeMatchesParametersH\x00R\n" +
	"parameters\x12^\n" +
	"\x0fbackfill_ticket\x18\x02 \x01(\v23.accelbyte.matchmaking.matchfunction.BackfillTicketH\x00R\x0ebackfillTicket\x12E\n" +
	"\x06ticket\x18\x03 \x01(\v2+.accelbyte.matchmaking.matchfunction.TicketH\x00R\x06ticket\x1a\xb3\x01\n" +
	"\x15MakeMatchesParameters\x12@\n" +
	"\x05scope\x18\x01 \x01(\v2*.accelbyte.matchmaking.matchfunction.ScopeR\x05scope\x12@\n" +
	"\x05rules\x18\x02 \x01(\v2*.accelbyte.matchmaking.matchfunction.RulesR\x05rules\x12\x16\n" +
	"\x06tickId\x18\x03 \x01(\x04R\x06tickIdB\x0e\n" +
	"\frequest_type\"v\n" +
	"\x10BackfillResponse\x12b\n" +
	"\x11backfill_proposal\x18\x01 \x01(\v25.accelbyte.matchmaking.matchfunction.BackfillProposalR\x10backfillProposal\"\x99\x06\n" +
	"\x0eBackfillTicket\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1d\n" +
	"\n" +
	"match_pool\x18\x02 \x01(\tR\tmatchPool\x128\n" +
	"\tCreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12e\n" +
	"\rpartial_match\x18\x04 \x01(\v2@.accelbyte.matchmaking.matchfunction.BackfillTicket.PartialMatchR\fpartialMatch\x12(\n" +
	"\x10match_session_id\x18\x05 \x01(\tR\x0ematchSessionId\x1a\x80\x01\n" +
	"\x04Team\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12D\n" +
	"\aparties\x18\x02 \x03(\v2*.accelbyte.matchmaking.matchfunction.PartyR\aparties\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x1a\xfc\x02\n" +
	"\fPartialMatch\x12E\n" +
	"\atickets\x18\x01 \x03(\v2+.accelbyte.matchmaking.matchfunction.TicketR\atickets\x12N\n" +
	"\x05teams\x18\x02 \x03(\v28.accelbyte.matchmaking.matchfunction.BackfillTicket.TeamR\x05teams\x12-\n" +
	"\x12region_preferences\x18\x03 \x03(\tR\x11regionPreferences\x12B\n" +
	"\x10match_attributes\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x0fmatchAttributes\x12\x1a\n" +
	"\bbackfill\x18\x05 \x01(\bR\bbackfill\x12\x1f\n" +
	"\vserver_name\x18\x06 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x0eclient_version\x18\a \x01(\tR\rclientVersion2\xb4\x05\n" +
	"\rMatchFunction\x12\x80\x01\n" +
	"\fGetStatCodes\x128.accelbyte.matchmaking.matchfunction.GetStatCodesRequest\x1a6.accelbyte.matchmaking.matchfunction.StatCodesResponse\x12\x89\x01\n" +
	"\x0eValidateTicket\x12:.accelbyte.matchmaking.matchfunction.ValidateTicketRequest\x1a;.accelbyte.matchmaking.matchfunction.ValidateTicketResponse\x12\x83\x01\n" +
	"\fEnrichTicket\x128.accelbyte.matchmaking.matchfunction.EnrichTicketRequest\x1a9.accelbyte.matchmaking.matchfunction.EnrichTicketResponse\x12~\n" +
	"\vMakeMatches\x127.accelbyte.matchmaking.matchfunction.MakeMatchesRequest\x1a2.accelbyte.matchmaking.matchfunction.MatchResponse(\x010\x01\x12\x8d\x01\n" +
	"\x0fBackfillMatches\x12?.accelbyte.matchmaking.matchfunction.BackfillMakeMatchesRequest\x1a5.accelbyte.matchmaking.matchfunction.BackfillResponse(\x010\x01B\x80\x01\n" +
	")net.accelbyte.matchmakingv2.matchfunctionP\x01Z)accelbyte.net/matchmakingv2/matchfunction\xaa\x02%AccelByte.MatchmakingV2.MatchFunctionb\x06proto3"

var (
	file_matchFunction_proto_rawDescOnce sync.Once
	file_matchFunction_proto_rawDescData []byte
)

func file_matchFunction_proto_rawDescGZIP() []byte {
	file_matchFunction_proto_rawDescOnce.Do(func() {
		file_matchFunction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matchFunction_proto_rawDesc), len(file_matchFunction_proto_rawDesc)))
	})
	return file_matchFunction_proto_rawDescData
}

var file_matchFunction_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_matchFunction_proto_goTypes = []any{
	(*GetStatCodesRequest)(nil),                      // 0: accelbyte.matchmaking.matchfunction.GetStatCodesRequest
	(*StatCodesResponse)(nil),                        // 1: accelbyte.matchmaking.matchfunction.StatCodesResponse
	(*ValidateTicketRequest)(nil),                    // 2: accelbyte.matchmaking.matchfunction.ValidateTicketRequest
	(*ValidateTicketResponse)(nil),                   // 3: accelbyte.matchmaking.matchfunction.ValidateTicketResponse
	(*EnrichTicketRequest)(nil),                      // 4: accelbyte.matchmaking.matchfunction.EnrichTicketRequest
	(*EnrichTicketResponse)(nil),                     // 5: accelbyte.matchmaking.matchfunction.EnrichTicketResponse
	(*MakeMatchesRequest)(nil),                       // 6: accelbyte.matchmaking.matchfunction.MakeMatchesRequest
	(*MatchResponse)(nil),                            // 7: accelbyte.matchmaking.matchfunction.MatchResponse
	(*Scope)(nil),                                    // 8: accelbyte.matchmaking.matchfunction.Scope
	(*Rules)(nil),                                    // 9: accelbyte.matchmaking.matchfunction.Rules
	(*Party)(nil),                                    // 10: accelbyte.matchmaking.matchfunction.Party
	(*Match)(nil),                                    // 11: accelbyte.matchmaking.matchfunction.Match
	(*ServerPool)(nil),                               // 12: accelbyte.matchmaking.matchfunction.ServerPool
	(*Ticket)(nil),                                   // 13: accelbyte.matchmaking.matchfunction.Ticket
	(*BackfillProposal)(nil),                         // 14: accelbyte.matchmaking.matchfunction.BackfillProposal
	(*BackfillMakeMatchesRequest)(nil),               // 15: accelbyte.matchmaking.matchfunction.BackfillMakeMatchesRequest
	(*BackfillResponse)(nil),                         // 16: accelbyte.matchmaking.matchfunction.BackfillResponse
	(*BackfillTicket)(nil),                           // 17: accelbyte.matchmaking.matchfunction.BackfillTicket
	(*MakeMatchesRequest_MakeMatchesParameters)(nil), // 18: accelbyte.matchmaking.matchfunction.MakeMatchesRequest.MakeMatchesParameters
	(*Match_Team)(nil),                               // 19: accelbyte.matchmaking.matchfunction.Match.Team
	(*Ticket_PlayerData)(nil),                        // 20: accelbyte.matchmaking.matchfunction.Ticket.PlayerData
	nil,                                              // 21: accelbyte.matchmaking.matchfunction.Ticket.LatenciesEntry
	(*BackfillProposal_Team)(nil),                    // 22: accelbyte.matchmaking.matchfunction.BackfillProposal.Team
	(*BackfillMakeMatchesRequest_MakeMatchesParameters)(nil), // 23: accelbyte.matchmaking.matchfunction.BackfillMakeMatchesRequest.MakeMatchesParameters
	(*BackfillTicket_Team)(nil),                              // 24: accelbyte.matchmaking.matchfunction.BackfillTicket.Team
	(*BackfillTicket_PartialMatch)(nil),                      // 25: accelbyte.matchmaking.matchfunction.BackfillTicket.PartialMatch
	(*structpb.Struct)(nil),                                  // 26: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),                            // 27: google.protobuf.Timestamp
}
var file_matchFunction_proto_depIdxs = []int32{
	9,  // 0: accelbyte.matchmaking.matchfunction.GetStatCodesRequest.rules:type_name -> accelbyte.matchmaking.matchfunction.Rules
	13, // 1: accelbyte.matchmaking.matchfunction.ValidateTicketRequest.ticket:type_name -> accelbyte.matchmaking.matchfunction.Ticket
	9,  // 2: accelbyte.matchmaking.matchfunction.ValidateTicketRequest.rules:type_name -> accelbyte.matchmaking.matchfunction.Rules
	13, // 3: accelbyte.matchmaking.matchfunction.EnrichTicketRequest.ticket:type_name -> accelbyte.matchmaking.matchfunction.Ticket
	9,  // 4: accelbyte.matchmaking.matchfunction.EnrichTicketRequest.rules:type_name -> accelbyte.matchmaking.matchfunction.Rules
	13, // 5: accelbyte.matchmaking.matchfunction.EnrichTicketResponse.ticket:type_name -> accelbyte.matchmaking.matchfunction.Ticket
	18, // 6: accelbyte.matchmaking.matchfunction.MakeMatchesRequest.parameters:type_name -> accelbyte.matchmaking.matchfunction.MakeMatchesRequest.MakeMatchesParameters
	13, // 7: accelbyte.matchmaking.matchfunction.MakeMatchesRequest.ticket:type_name -> accelbyte.matchmaking.matchfunction.Ticket
	11, // 8: accelbyte.matchmaking.matchfunction.MatchResponse.match:type_name -> accelbyte.matchmaking.matchfunction.Match
	13, // 9: accelbyte.matchmaking.matchfunction.Match.tickets:type_name -> accelbyte.matchmaking.matchfunction.Ticket
	19, // 10: accelbyte.matchmaking.matchfunction.Match.teams:type_name -> accelbyte.matchmaking.matchfunction.Match.Team
	26, // 11: accelbyte.matchmaking.matchfunction.Match.match_attributes:type_name -> google.protobuf.Struct
	12, // 12: accelbyte.matchmaking.matchfunction.Match.server_pool:type_name -> accelbyte.matchmaking.matchfunction.ServerPool
	27, // 13: accelbyte.matchmaking.matchfunction.Ticket.CreatedAt:type_name -> google.protobuf.Timestamp
	20, // 14: accelbyte.matchmaking.matchfunction.Ticket.players:type_name -> accelbyte.matchmaking.matchfunction.Ticket.PlayerData
	26, // 15: accelbyte.matchmaking.matchfunction.Ticket.ticket_attributes:type_name -> google.protobuf.Struct
	21, // 16: accelbyte.matchmaking.matchfunction.Ticket.latencies:type_name -> accelbyte.matchmaking.matchfunction.Ticket.LatenciesEntry
	27, // 17: accelbyte.matchmaking.matchfunction.BackfillProposal.CreatedAt:type_name -> google.protobuf.Timestamp
	13, // 18: accelbyte.matchmaking.matchfunction.BackfillProposal.added_tickets:type_name -> accelbyte.matchmaking.matchfunction.Ticket
	22, // 19: accelbyte.matchmaking.matchfunction.BackfillProposal.proposed_teams:type_name -> accelbyte.matchmaking.matchfunction.BackfillProposal.Team
	26, // 20: accelbyte.matchmaking.matchfunction.BackfillProposal.attributes:type_name -> google.protobuf.Struct
	23, // 21: accelbyte.matchmaking.matchfunction.BackfillMakeMatchesRequest.parameters:type_name -> accelbyte.matchmaking.matchfunction.BackfillMakeMatchesRequest.MakeMatchesParameters
	17, // 22: accelbyte.matchmaking.matchfunction.BackfillMakeMatchesRequest.backfill_ticket:type_name -> accelbyte.matchmaking.matchfunction.BackfillTicket
	13, // 23: accelbyte.matchmaking.matchfunction.BackfillMakeMatchesRequest.ticket:type_name -> accelbyte.matchmaking.matchfunction.Ticket
	14, // 24: accelbyte.matchmaking.matchfunction.BackfillResponse.backfill_proposal:type_name -> accelbyte.matchmaking.matchfunction.BackfillProposal
	27, // 25: accelbyte.matchmaking.matchfunction.BackfillTicket.CreatedAt:type_name -> google.protobuf.Timestamp
	25, // 26: accelbyte.matchmaking.matchfunction.BackfillTicket.partial_match:type_name -> accelbyte.matchmaking.matchfunction.BackfillTicket.PartialMatch
	8,  // 27: accelbyte.matchmaking.matchfunction.MakeMatchesRequest.MakeMatchesParameters.scope:type_name -> accelbyte.matchmaking.matchfunction.Scope
	9,  // 28: accelbyte.matchmaking.matchfunction.MakeMatchesRequest.MakeMatchesParameters.rules:type_name -> accelbyte.matchmaking.matchfunction.Rules
	10, // 29: accelbyte.matchmaking.matchfunction.Match.Team.parties:type_name -> accelbyte.matchmaking.matchfunction.Party
	26, // 30: accelbyte.matchmaking.matchfunction.Ticket.PlayerData.attributes:type_name -> google.protobuf.Struct
	10, // 31: accelbyte.matchmaking.matchfunction.BackfillProposal.Team.parties:type_name -> accelbyte.matchmaking.matchfunction.Party
	8,  // 32: accelbyte.matchmaking.matchfunction.BackfillMakeMatchesRequest.MakeMatchesParameters.scope:type_name -> accelbyte.matchmaking.matchfunction.Scope
	9,  // 33: accelbyte.matchmaking.matchfunction.BackfillMakeMatchesRequest.MakeMatchesParameters.rules:type_name -> accelbyte.matchmaking.matchfunction.Rules
	10, // 34: accelbyte.matchmaking.matchfunction.BackfillTicket.Team.parties:type_name -> accelbyte.matchmaking.matchfunction.Party
	13, // 35: accelbyte.matchmaking.matchfunction.BackfillTicket.PartialMatch.tickets:type_name -> accelbyte.matchmaking.matchfunction.Ticket
	24, // 36: accelbyte.matchmaking.matchfunction.BackfillTicket.PartialMatch.teams:type_name -> accelbyte.matchmaking.matchfunction.BackfillTicket.Team
	26, // 37: accelbyte.matchmaking.matchfunction.BackfillTicket.PartialMatch.match_attributes:type_name -> google.protobuf.Struct
	0,  // 38: accelbyte.matchmaking.matchfunction.MatchFunction.GetStatCodes:input_type -> accelbyte.matchmaking.matchfunction.GetStatCodesRequest
	2,  // 39: accelbyte.matchmaking.matchfunction.MatchFunction.ValidateTicket:input_type -> accelbyte.matchmaking.matchfunction.ValidateTicketRequest
	4,  // 40: accelbyte.matchmaking.matchfunction.MatchFunction.EnrichTicket:input_type -> accelbyte.matchmaking.matchfunction.EnrichTicketRequest
	6,  // 41: accelbyte.matchmaking.matchfunction.MatchFunction.MakeMatches:input_type -> accelbyte.matchmaking.matchfunction.MakeMatchesRequest
	15, // 42: accelbyte.matchmaking.matchfunction.MatchFunction.BackfillMatches:input_type -> accelbyte.matchmaking.matchfunction.BackfillMakeMatchesRequest
	1,  // 43: accelbyte.matchmaking.matchfunction.MatchFunction.GetStatCodes:output_type -> accelbyte.matchmaking.matchfunction.StatCodesResponse
	3,  // 44: accelbyte.matchmaking.matchfunction.MatchFunction.ValidateTicket:output_type -> accelbyte.matchmaking.matchfunction.ValidateTicketResponse
	5,  // 45: accelbyte.matchmaking.matchfunction.MatchFunction.EnrichTicket:output_type -> accelbyte.matchmaking.matchfunction.EnrichTicketResponse
	7,  // 46: accelbyte.matchmaking.matchfunction.MatchFunction.MakeMatches:output_type -> accelbyte.matchmaking.matchfunction.MatchResponse
	16, // 47: accelbyte.matchmaking.matchfunction.MatchFunction.BackfillMatches:output_type -> accelbyte.matchmaking.matchfunction.BackfillResponse
	43, // [43:48] is the sub-list for method output_type
	38, // [38:43] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_matchFunction_proto_init() }
func file_matchFunction_proto_init() {
	if File_matchFunction_proto != nil {
		return
	}
	file_matchFunction_proto_msgTypes[6].OneofWrappers = []any{
		(*MakeMatchesRequest_Parameters)(nil),
		(*MakeMatchesRequest_Ticket)(nil),
	}
	file_matchFunction_proto_msgTypes[15].OneofWrappers = []any{
		(*BackfillMakeMatchesRequest_Parameters)(nil),
		(*BackfillMakeMatchesRequest_BackfillTicket)(nil),
		(*BackfillMakeMatchesRequest_Ticket)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matchFunction_proto_rawDesc), len(file_matchFunction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matchFunction_proto_goTypes,
		DependencyIndexes: file_matchFunction_proto_depIdxs,
		MessageInfos:      file_matchFunction_proto_msgTypes,
	}.Build()
	File_matchFunction_proto = out.File
	file_matchFunction_proto_goTypes = nil
	file_matchFunction_proto_depIdxs = nil
}
